/// Flutter icons ActionButtonIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ActionButtonIcon
///      fonts:
///       - asset: fonts/ActionButtonIcon.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class ActionButtonIcon {
  ActionButtonIcon._();

  static const _kFontFam = 'ActionButtonIcon';
  static const String _kFontPkg = null;

  static const IconData leaf = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medal = IconData(0xf5a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
